### ISSUE TITLE
Sorry if I'm annoying but sub branch update? 

### ISSUE THREAD

**Issue by Turhvjbufv** [KhoalaS/Infinity-For-Reddit#1]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.0.3

### Where did you get the app from

Other

### Android version

doesn't matter

### Steps to reproduce

No bug just wanted to ask, main branch got many updates when does sub branch get those too?

**Comment by KhoalaS** [comment]
The only goal of the sub-branch is just to enable custom Client-ID and User-agent input. Users are supposed to be compliant with the User-Agreement in that version.

All the features of the main branch are only possible with breaking the User-Agreement and risking a ban.

**Comment by Turhvjbufv** [comment]
Just wanna make sure, so technically the sub branch is okay with the user agreement of reddit but main isn't?
