### ISSUE TITLE
List of suggested subreddits don't show while searching in anonymous mode

### ISSUE THREAD

**Issue by Raven-621** [KhoalaS/Infinity-For-Reddit#10]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.9.2

### Where did you get the app from

Other

### Android version

10, One UI 2.0

### Steps to reproduce

- Press search icon
- Look for something, for example: looking for r/natureismetal by just typing "nature"

### Expected behaviour

A list of recommended subreddits based on the word typed should show up in result (without pressing search button) after a few seconds

### Current behaviour

None of the list showed up. Tried with multiple words. I know that you could just press the search button and search via the subreddit tab, but at least to me, it'll be nice if this is possible

> Tho tbh, i only knew that feature for so long while i was logged in and never tried in anonymous mode, so sorry for bothering if this is impossible in anonymous mode

![Screenshot_20230815-173045_Reddit](https://github.com/KhoalaS/Infinity-For-Reddit/assets/141109979/dc791e3a-7af7-4b9b-8931-075e44c2d6fa)

**Comment by Turhvjbufv** [comment]
@KhoalaS please close this as not planned as it can confuse
