### ISSUE TITLE
Add the possibility to view an image in fullscreen

### ISSUE THREAD

**Issue by jojobozo** [KhoalaS/Infinity-For-Reddit#11]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.9.2

### Where did you get the app from

Other

### Android version

13

### Current behaviour

Adding the possibility to view an image in fullscreen would be great because in some images we can't really see the text and details too.
![Screenshot_20230815-205233](https://github.com/KhoalaS/Infinity-For-Reddit/assets/98482700/bb2e8c44-5a3a-4610-84d4-8e7621500113)

**Comment by emmaexe** [comment]
Seconded. This also affects text posts with images, no matter if there is any text in the post or not. If not possible easily at least add a feature that allows us to go back to the sticker/emoji text links in comments and links in posts.

I loved being able to open any media on reddit in fullscreen and view or download it.

**Comment by KhoalaS** [comment]
Added with 268f1b5fda2dba00b633c8e7997d9142951eacef and ef5dcc9e4d6e641f50b6bdab145065f7384132c8.
Will be in next release.

Commit message says it's for comments but it also works for media in posts.

If you encounter crashes during download, post the link to the media here.

**Comment by Turhvjbufv** [comment]
@KhoalaS close as completed
