### ISSUE TITLE
please update to docile alligator recent releases 

### ISSUE THREAD

**Issue by Turhvjbufv** [KhoalaS/Infinity-For-Reddit#15]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.10.0

### Where did you get the app from

Other

### Android version

doesn't matter

**Comment by KhoalaS** [comment]
Done in cbc7a1c50fcd9dc44430ade14bbe69aaeb971efb and d79a1b94630afb473acdadc788437c5343431d23 on experimental branch.

I am still testing it myself. Will go to main if I don't encounter any bugs.

**Comment by Turhvjbufv** [comment]
Btw did you fix Android 13 login issue?

**Comment by KhoalaS** [comment]
I still dont know when it happens. It occured once on my Android 13 emulator but was working fine on the latest release. 
Coincidentally I get the error on my Android 11 emulator but it works on my Android 11 device. 
The HTTP Response says it's an INVALID_SIGNATURE error.

**Comment by KhoalaS** [comment]
I reverted back to not merging the updates since there are performance issues and merging with upstream is a headache.

**Comment by Turhvjbufv** [comment]
Then close as not planned

**Comment by Felting** [comment]
> I reverted back to not merging the updates since there are performance issues and merging with upstream is a headache.

What version of docile alligator's is it based on?
