### ISSUE TITLE
What to do after getting banned ?

### ISSUE THREAD

**Issue by IndusAryan** [KhoalaS/Infinity-For-Reddit#16]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

Latest

### Where did you get the app from

Other

### Android version

A13

### Device model

RN7 Lavender

### First occurred

today

### Steps to reproduce

So i got banned today , i will close this issue as fast as i can after getting answers from anyone.

### Example post, link, markdown...

whether i should appeal its upto me but if i create another account should i use KhoalaS infinity any more or not or should i use the Client ID input version or the normal infinity by Docile alligator by pathcing my ID through revanced manager,etc|

### Expected behaviour

asking this because Khoala version sends custom disguised requests by which our accoounts are getting banned.

**Comment by Turhvjbufv** [comment]
Don't appeal it won't work

**Comment by Turhvjbufv** [comment]
Getting banned from reddit just means that you aren't able to do any action on the site except viewing it

**Comment by DraconicNEO** [comment]
Make a new account on Tor using a different email or no email.
