### ISSUE TITLE
Home feed doesn't load

### ISSUE THREAD

**Issue by Raven-621** [KhoalaS/Infinity-For-Reddit#2]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.7.0

### Where did you get the app from

Other

### Android version

10, One UI 2.0

### Steps to reproduce

Open the app, and it'll show you the home feed as the first page you'll see

### Expected behaviour

Home feed would load with posts from subbed subreddits

### Current behaviour

The home feed keeps giving error (i tried with using VPN, still the same. So it's not due to my Internet)
![Screenshot_20230803-143244_Infinity](https://github.com/KhoalaS/Infinity-For-Reddit/assets/141109979/01750fd1-3071-4898-b1f0-e97e02efa0b8)

**Comment by KhoalaS** [comment]
Does the feed load if you go to a specific Subreddit?

**Comment by Raven-621** [comment]
> Does the feed load if you go to a specific Subreddit?

Yes, the feed for subreddits works just fine.

(Top is r/oddlysatisfying while bottom is r/linux)
![Screenshot_20230804-214010_Infinity](https://github.com/KhoalaS/Infinity-For-Reddit/assets/141109979/b30e585e-27c9-46ef-ba3f-8836812ccb94)
![Screenshot_20230804-214023_Infinity](https://github.com/KhoalaS/Infinity-For-Reddit/assets/141109979/fc985885-0406-47e8-b5df-4d1002e4f715)

**Comment by Raven-621** [comment]
> Hmm. This might be related to bugs in earlier versions, mainly 5.6.1.
> 
> Logging out and logging in again might work to reset faulty SharedPreference Files.

Just tried it earlier. Still the same result (error).

**Comment by KhoalaS** [comment]
Fixed in ba6ec9503e1d9717d5b8917bb315c485d77a360d

Update is building right now.
