### ISSUE TITLE
Mismatch between github version and apk version

### ISSUE THREAD

**Issue by emmaexe** [KhoalaS/Infinity-For-Reddit#20]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.12.0

### Where did you get the app from

Other

### Android version

MIUI Global 14.0.5 (Android 12 SKQ1.211019.001)

### Device model

Poco X3 NFC

### Example post, link, markdown...

The version of the apk/app when installed is 2023.31.0 following reddit's version scheme. However, infinity for reddit's version on github is currently 5.12.0. This mismatch causes issues when using app installers/updaters like [obtainium](https://github.com/ImranR98/Obtainium) since github releases reports the latest version differently from the app itself. Since the app isn't available on repositories like f-droid, it would be nice if it functioned better with obtainium. Obtainium does have built-in estimation for situations like this but it is not perfect, and does not work in all situations.

![obtainium](https://github.com/KhoalaS/Infinity-For-Reddit/assets/42188518/4a186271-7dab-4502-a298-0f0539f37600)

### Expected behaviour

Version on github matches actual app version or vice versa.

### Current behaviour

Versions don't match. There is no version detection available. The app thinks there is an update, even though I have 5.12.0 installed.

**Comment by KhoalaS** [comment]
Yeah, I did this cause the app version is sometimes pulled for some generic network calls.
I willI start incrementing/releasing the versions according to Reddits scheme on the next release.
