### ISSUE TITLE
images that have text added to them don't show text

### ISSUE THREAD

**Issue by Turhvjbufv** [KhoalaS/Infinity-For-Reddit#21]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.12.0

### Where did you get the app from

Other

### Android version

Android 12

### Steps to reproduce

Find a image post that also have txt on reddit (example: https://www.reddit.com/r/manhwa/comments/17izb1a/revenge_of_the_ironblooded_sword_hound_why_i_hate/)
Open on official reddit app and you will see text bellow the image but on infinity you will only see image which is annoying

**Comment by KhoalaS** [comment]
I'll look into it

**Comment by Turhvjbufv** [comment]
Any Update?

**Comment by KhoalaS** [comment]
Yea it's fixed. I intended to roll it out together with a real fix for the new Collectible Expressions but that was taking me longer than expected.
