### ISSUE TITLE
customize tabs in main menu "saved" 

### ISSUE THREAD

**Issue by Turhvjbufv** [KhoalaS/Infinity-For-Reddit#3]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.7.2

### Where did you get the app from

Other

### Android version

Android 12

### First occurred

just downloaded 5.7.2 and it happened 

### Steps to reproduce

Do a "saved" tab in customize tabs in main menu and it will show your user tab,even if you don't have any user tab(btw yes I restarted the app to check this)

### Expected behaviour

Shows your saved post

### Current behaviour

Shows your profile page(aka user page)

**Comment by KhoalaS** [comment]
Identified the responsible code. Working on a fix for all the "Post" tabs.
