### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by YashSoPro** [KhoalaS/Infinity-For-Reddit#30]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

latest

### Where did you get the app from

Other

### Android version

11

### Device model

RMX3269

### Steps to reproduce

your project is live saver since in infinity for reddit new updates if we want add a account we have to buy a subscription because they say reddit charges for api and in your fork we don't have to buy any subscription so i wish if you could update it!

**Comment by hetszunyukapanyanyimonyok** [comment]
@KhoalaS Please, if you have time update it! Thank you!

**Comment by spider1163** [comment]
New release today

https://github.com/KhoalaS/Infinity-For-Reddit/releases
