### ISSUE TITLE
Home feed won't load in anonymous mode

### ISSUE THREAD

**Issue by Raven-621** [KhoalaS/Infinity-For-Reddit#33]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

Recent version (2023.32.0 and 2023.34.0, other versions might be affected)

### Where did you get the app from

Other

### Android version

Android 10 (OneUI 2.0)

### Device model

SM-A605G

### First occurred

Last week, i think

### Steps to reproduce

1. Open the app
2. The first page to appear is the home feed tab

### Expected behaviour

The home feed will load with subscribed subreddits in anonymous (i tried to view the home feed in the original Infinity, it works)

### Current behaviour

Persistent "error loading posts", even if you're using VPN.
![Screenshot_20240605-152108_Reddit](https://github.com/KhoalaS/Infinity-For-Reddit/assets/141109979/771b91c0-640a-4004-8317-bd23cd8d9fee)

**Comment by xusiai** [comment]
Happens for subreddits too. Seem to be more frequent with nsfw marked subreddits but not exclusive to them. This issue started occurring in v2023.32.1. It was then resolved with v2023.33.1
and then ceased working once more in v2023.34.0.

**Comment by KhoalaS** [comment]
Fixed in 817067c.
