### ISSUE TITLE
opening a child comments keeps them open on app close

### ISSUE THREAD

**Issue by Turhvjbufv** [KhoalaS/Infinity-For-Reddit#36]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

2023.37.0

### Where did you get the app from

Other

### Android version

Android 14

### Steps to reproduce

Open a comment by pressing on it to view child comments 
Then close the app and go back to the post you opened the comment, the child comments stay open even tho they should, and also the app doesn't register that they are open
![Screenshot_20240624-160550_Reddit_1_1](https://github.com/KhoalaS/Infinity-For-Reddit/assets/91851160/ffd36275-02d9-4788-a7ed-a45974289a8f)
As you can see, it shows that there 3 child comments that are not open, even tho they are

**Comment by KhoalaS** [comment]
I couldnt reproduce it. Can you send me a screenshot of your settings > interface > comment if you changed it?
