### ISSUE TITLE
error searching subreddits

### ISSUE THREAD

**Issue by Turhvjbufv** [KhoalaS/Infinity-For-Reddit#38]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

2024.02.0

### Where did you get the app from

Other

### Android version

android 14

### Steps to reproduce

Search for a subreddit

### Expected behaviour

Show a list of subreddits 

### Current behaviour

Error searching for subreddits

**Comment by KhoalaS** [comment]
Tested on banned account and still working. I'll try bumping up the target SDK to 34 (Android 14), its currently at 33.

**Comment by KhoalaS** [comment]
fixed in c995730f2fc1bcc7af23879aca460e9708127306
