### ISSUE TITLE
Material You theme does not update upon launch of app

### ISSUE THREAD

**Issue by coxackie** [KhoalaS/Infinity-For-Reddit#4]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.8.0

### Where did you get the app from

Other

### Android version

13

### Steps to reproduce

1. Choose "Material You" theme
2. Close the application
3. Change wallpaper
4. Enter Infinity
5. Colour palette is the same as before

### Expected behaviour

Material you theme should attempt to update the palette every time that the app launches

### Current behaviour

Material You theme is applied once selected at the current derived colour scheme and does not update is the wallpaper changes. One can only update it manually.

**Comment by KhoalaS** [comment]
Fixed in 8e170d8cdeafa63ca3a1c53830c2a088f1825ddd.
Will be included in next release.

**Comment by coxackie** [comment]
@KhoalaS thanks a lot for this. Just a quick question: I see this checks for wallpaper _change_ upon app launch. What happens with live wallpapers that change (for example, with time of the day or weather)? The wallpaper itself will not have changed, it would just be a different instance of the live wallpaper.

**Comment by KhoalaS** [comment]
The original implementation uses Intent Filters that check for a wallpaper change.
It will not update the colors if a live wallpaper changes it's colors.
I'll look into it though.
