### ISSUE TITLE
Anonymous browsing don't load subreddits

### ISSUE THREAD

**Issue by nateRiver111** [KhoalaS/Infinity-For-Reddit#7]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.9.0 master branch

### Where did you get the app from

Other

### Android version

10

### Steps to reproduce

1. Don't log in
2. Subscribe to a subreddit
3. Use the side panel to go to the subreddit
4. It gives "Cannot fetch subreddit" error

### Expected behaviour

To load the subreddits

### Current behaviour

Gives an "Error loading posts. Tap to retry"

**Comment by mitomenai** [comment]
@KhoalaS I haven't looked at the source code, but it should technically be possible to bypass the need for app API key entirely and use oauth.reddit.com directly with a user oauth token just like the website. Give it a generic user agent like Chrome and it should be fairly undetectable. What do you think?
